version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
        - n 18

  build:
    commands:
      - cd tbGameSpa
      - npm ci
      - npm run build

artifacts:
  files:
    - '**/*'
