version: 0.2

phases:
  install:
    install:
      runtime-versions:
        nodejs: 14
        commands:
          - n 18
    commands:
      - cd tbGameSpa
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
