version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd tbGameSpa
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
